#include "ItemsInitializer.h"

#include "Item.h"
#include "Weapon.h"
#include "Miscellaneous.h"

#include <string>
#include <map>
#include <memory>

using std::string;
using std::map;
using std::shared_ptr;
using std::make_shared;

// Initialize a map that statically stores shared_ptr<Item> associated with shared ItemsIndex
const map<ItemsInitializer::ItemsIndex, shared_ptr<Item>> ItemsInitializer::getItems() {
    // By using shared_ptr<Item> we can polymorphically initializes objects of its subclasses
    static map<ItemsInitializer::ItemsIndex, shared_ptr<Item>> Items {
        {ItemsIndex::_START_, make_shared<Miscellaneous>()},
        // Miscellaneous - Tools
        {ItemsIndex::WOODEN_HAMMER, make_shared<Miscellaneous>("Wooden Hammer", 3.5, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::IRON_TONGS, make_shared<Miscellaneous>("Iron Tongs", 2.0, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::LEATHER_POUCH, make_shared<Miscellaneous>("Leather Pouch", 0.5, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::CARPENTER_SAW, make_shared<Miscellaneous>("Carpenter's Saw", 3.0, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::BLACKSMITH_HAMMER, make_shared<Miscellaneous>("Blacksmith's Hammer", 5.0, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::HUNTER_TRAP, make_shared<Miscellaneous>("Hunter's Trap", 4.0, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::FISHING_ROD, make_shared<Miscellaneous>("Fishing Rod", 1.5, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::COOKING_POT, make_shared<Miscellaneous>("Cooking Pot", 6.0, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::TOOL)},
        {ItemsIndex::HEALER_KIT, make_shared<Miscellaneous>("Healer's Kit", 2.5, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::TOOL)},

        // Miscellaneous - Magical Items
        {ItemsIndex::ENCHANTED_STONE, make_shared<Miscellaneous>("Enchanted Stone", 1.0, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::ALCHEMIST_KIT, make_shared<Miscellaneous>("Alchemist's Kit", 3.0, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::MYSTIC_TALISMAN, make_shared<Miscellaneous>("Mystic Talisman", 0.3, Item::ItemRarities::EPIC, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::ANCIENT_SCROLL, make_shared<Miscellaneous>("Ancient Scroll", 0.2, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::WIZARD_CLOAK, make_shared<Miscellaneous>("Wizard's Cloak", 2.2, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::MAGE_ORB, make_shared<Miscellaneous>("Mage's Orb", 1.0, Item::ItemRarities::EPIC, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::SHIMMERING_CRYSTAL, make_shared<Miscellaneous>("Shimmering Crystal", 0.5, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::TELEPORTATION_RUNE, make_shared<Miscellaneous>("Teleportation Rune", 0.1, Item::ItemRarities::LEGENDARY, Miscellaneous::MiscellaneousCategories::MAGICAL)},
        {ItemsIndex::CURSED_RING, make_shared<Miscellaneous>("Cursed Ring", 0.1, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::MAGICAL)},

        // Miscellaneous - Food
        {ItemsIndex::DRIED_MEAT, make_shared<Miscellaneous>("Dried Meat", 0.8, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::HEALING_HERBS, make_shared<Miscellaneous>("Healing Herbs", 0.3, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::APPLE, make_shared<Miscellaneous>("Apple", 0.2, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::HONEY_JAR, make_shared<Miscellaneous>("Honey Jar", 1.0, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::BREAD_LOAF, make_shared<Miscellaneous>("Bread Loaf", 0.5, Item::ItemRarities::COMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::CHEESE_WHEEL, make_shared<Miscellaneous>("Cheese Wheel", 1.5, Item::ItemRarities::UNCOMMON, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::HERB_SOUP, make_shared<Miscellaneous>("Herb Soup", 0.8, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::SPICED_WINE, make_shared<Miscellaneous>("Spiced Wine", 0.7, Item::ItemRarities::RARE, Miscellaneous::MiscellaneousCategories::FOOD)},
        {ItemsIndex::DRAGONFRUIT, make_shared<Miscellaneous>("Dragonfruit", 0.4, Item::ItemRarities::EPIC, Miscellaneous::MiscellaneousCategories::FOOD)},

        // Weapons - Swords
        {ItemsIndex::IRON_SWORD, make_shared<Weapon>("Iron Sword", 10, Item::ItemRarities::COMMON, 10, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STEEL_SHORT_SWORD, make_shared<Weapon>("Steel Short Sword", 12, Item::ItemRarities::UNCOMMON, 12, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BRONZE_LONG_SWORD, make_shared<Weapon>("Bronze Long Sword", 14, Item::ItemRarities::COMMON, 14, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::KNIGHT_BLADE, make_shared<Weapon>("Knight Blade", 15, Item::ItemRarities::RARE, 15, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::ASSASSIN_DAGGER, make_shared<Weapon>("Assassin Dagger", 5, Item::ItemRarities::EPIC, 25, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::RUNE_SWORD, make_shared<Weapon>("Rune Sword", 11, Item::ItemRarities::RARE, 20, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::SILVER_RAPIER, make_shared<Weapon>("Silver Rapier", 8, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::SHADOW_FANG, make_shared<Weapon>("Shadow Fang", 7, Item::ItemRarities::EPIC, 22, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BLOODTHIRST_BLADE, make_shared<Weapon>("Bloodthirst Blade", 13, Item::ItemRarities::LEGENDARY, 30, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::CELESTIAL_SABER, make_shared<Weapon>("Celestial Saber", 9, Item::ItemRarities::UNIQUE, 35, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::FROSTBITE_BLADE, make_shared<Weapon>("Frostbite Blade", 14, Item::ItemRarities::RARE, 22, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::FLAME_TONGUE, make_shared<Weapon>("Flame Tongue", 13, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::STARFIRE_SHORT_SWORD, make_shared<Weapon>("Starfire Short Sword", 10, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::BLADE_OF_THE_WINDS, make_shared<Weapon>("Blade of the Winds", 12, Item::ItemRarities::LEGENDARY, 35, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::ECLIPSE_SWORD, make_shared<Weapon>("Eclipse Sword", 16, Item::ItemRarities::EPIC, 32, Weapon::WeaponCategories::SWORD, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MELEE)},

		// Weapons - Greatswords
		{ItemsIndex::IRON_GREATSWORD, make_shared<Weapon>("Iron Greatsword", 20, Item::ItemRarities::COMMON, 25, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SILVER_GREATSWORD, make_shared<Weapon>("Silver Greatsword", 22, Item::ItemRarities::UNCOMMON, 28, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DRAGON_SLAYER, make_shared<Weapon>("Dragon Slayer", 35, Item::ItemRarities::RARE, 50, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DARKSTEEL_CLAYMORE, make_shared<Weapon>("Darksteel Claymore", 28, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::ANCIENT_BLADE, make_shared<Weapon>("Ancient Blade", 32, Item::ItemRarities::LEGENDARY, 55, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::TITAN_SWORD, make_shared<Weapon>("Titan Sword", 40, Item::ItemRarities::EPIC, 60, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::BERSERKER_CLAYMORE, make_shared<Weapon>("Berserker Claymore", 30, Item::ItemRarities::RARE, 45, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SUNFORGED_GREATSWORD, make_shared<Weapon>("Sunforged Greatsword", 34, Item::ItemRarities::LEGENDARY, 65, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DOOMBRINGER, make_shared<Weapon>("Doombringer", 38, Item::ItemRarities::EPIC, 58, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::OBSIDIAN_GREATBLADE, make_shared<Weapon>("Obsidian Greatblade", 36, Item::ItemRarities::RARE, 48, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::CRUSADER_GREATSWORD, make_shared<Weapon>("Crusader Greatsword", 26, Item::ItemRarities::UNCOMMON, 33, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::WARLORD_BLADE, make_shared<Weapon>("Warlord Blade", 31, Item::ItemRarities::RARE, 52, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::THUNDERCLAP_GREATSWORD, make_shared<Weapon>("Thunderclap Greatsword", 29, Item::ItemRarities::EPIC, 49, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::LIGHTBRINGER_BLADE, make_shared<Weapon>("Lightbringer Blade", 27, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::ABYSSAL_CLEAVER, make_shared<Weapon>("Abyssal Cleaver", 33, Item::ItemRarities::UNIQUE, 70, Weapon::WeaponCategories::GREATSWORD, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},

        // Weapon - Axes
        {ItemsIndex::IRON_AXE, make_shared<Weapon>("Iron Axe", 12, Item::ItemRarities::COMMON, 15, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STEEL_BATTLEAXE, make_shared<Weapon>("Steel Battleaxe", 14, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BRONZE_HANDAXE, make_shared<Weapon>("Bronze Handaxe", 10, Item::ItemRarities::COMMON, 12, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BATTLE_AXE_OF_THE_KING, make_shared<Weapon>("Battle Axe of the King", 20, Item::ItemRarities::RARE, 30, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::ELVEN_WARAXE, make_shared<Weapon>("Elven Waraxe", 18, Item::ItemRarities::UNCOMMON, 25, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::FROST_AXE, make_shared<Weapon>("Frost Axe", 22, Item::ItemRarities::RARE, 35, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::RUNE_AXE, make_shared<Weapon>("Rune Axe", 25, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::MYSTIC_AXE, make_shared<Weapon>("Mystic Axe", 28, Item::ItemRarities::LEGENDARY, 50, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::THUNDERSTRIKE_AXE, make_shared<Weapon>("Thunderstrike Axe", 30, Item::ItemRarities::EPIC, 45, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::DARKWOOD_AXE, make_shared<Weapon>("Darkwood Axe", 19, Item::ItemRarities::UNCOMMON, 28, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BLOODAXE, make_shared<Weapon>("Bloodaxe", 23, Item::ItemRarities::RARE, 38, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::FIREAXE, make_shared<Weapon>("Fireaxe", 27, Item::ItemRarities::EPIC, 50, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::CELESTIAL_BATTLEAXE, make_shared<Weapon>("Celestial Battleaxe", 32, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::VAMPIRIC_AXE, make_shared<Weapon>("Vampiric Axe", 29, Item::ItemRarities::RARE, 55, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STORMAXE, make_shared<Weapon>("Stormaxe", 35, Item::ItemRarities::EPIC, 65, Weapon::WeaponCategories::AXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},

        // Weapon - Greataxes
        {ItemsIndex::IRON_GREATAXE, make_shared<Weapon>("Iron Greataxe", 15, Item::ItemRarities::COMMON, 25, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STEEL_GREATAXE, make_shared<Weapon>("Steel Greataxe", 18, Item::ItemRarities::UNCOMMON, 30, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::TITAN_GREATAXE, make_shared<Weapon>("Titan Greataxe", 30, Item::ItemRarities::RARE, 50, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::DRAGONBONE_GREATAXE, make_shared<Weapon>("Dragonbone Greataxe", 35, Item::ItemRarities::EPIC, 60, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::DEMONIC_GREATAXE, make_shared<Weapon>("Demonic Greataxe", 40, Item::ItemRarities::LEGENDARY, 70, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::SUNFORGED_GREATAXE, make_shared<Weapon>("Sunforged Greataxe", 45, Item::ItemRarities::LEGENDARY, 80, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::CRYSTAL_GREATAXE, make_shared<Weapon>("Crystal Greataxe", 38, Item::ItemRarities::RARE, 55, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::WARLORD_GREATAXE, make_shared<Weapon>("Warlord Greataxe", 36, Item::ItemRarities::EPIC, 70, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::OBSIDIAN_GREATAXE, make_shared<Weapon>("Obsidian Greataxe", 42, Item::ItemRarities::EPIC, 75, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::FROSTGREATAXE, make_shared<Weapon>("Frost Greataxe", 33, Item::ItemRarities::RARE, 65, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BERSERKER_GREATAXE, make_shared<Weapon>("Berserker Greataxe", 28, Item::ItemRarities::RARE, 60, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STORMGREATAXE, make_shared<Weapon>("Storm Greataxe", 40, Item::ItemRarities::LEGENDARY, 85, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::CELESTIAL_GREATAXE, make_shared<Weapon>("Celestial Greataxe", 50, Item::ItemRarities::LEGENDARY, 95, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BLOODTHIRST_GREATAXE, make_shared<Weapon>("Bloodthirst Greataxe", 45, Item::ItemRarities::RARE, 80, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::ECLIPSE_GREATAXE, make_shared<Weapon>("Eclipse Greataxe", 38, Item::ItemRarities::EPIC, 72, Weapon::WeaponCategories::GREATAXE, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		
        // Weapons - Polearms
		{ItemsIndex::IRON_LANCE, make_shared<Weapon>("Iron Lance", 11, Item::ItemRarities::COMMON, 12, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::STEEL_SPEAR, make_shared<Weapon>("Steel Spear", 14, Item::ItemRarities::UNCOMMON, 16, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::PIKE, make_shared<Weapon>("Pike", 16, Item::ItemRarities::RARE, 20, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::HALBERD, make_shared<Weapon>("Halberd", 18, Item::ItemRarities::RARE, 25, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DRAGONBONE_TRIDENT, make_shared<Weapon>("Dragonbone Trident", 22, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::GLAIVE, make_shared<Weapon>("Glaive", 17, Item::ItemRarities::UNCOMMON, 21, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::LONG_POLEAXE, make_shared<Weapon>("Long Poleaxe", 19, Item::ItemRarities::RARE, 26, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::PHANTOM_SPEAR, make_shared<Weapon>("Phantom Spear", 25, Item::ItemRarities::EPIC, 35, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::VANGUARD_LANCE, make_shared<Weapon>("Vanguard Lance", 21, Item::ItemRarities::RARE, 28, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::WAR_PIKE, make_shared<Weapon>("War Pike", 20, Item::ItemRarities::EPIC, 33, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SPEAR_OF_DESTINY, make_shared<Weapon>("Spear of Destiny", 24, Item::ItemRarities::LEGENDARY, 45, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::FROST_HALBERD, make_shared<Weapon>("Frost Halberd", 23, Item::ItemRarities::EPIC, 38, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::FIERY_GLAIVE, make_shared<Weapon>("Fiery Glaive", 20, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::SLASH, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::TWILIGHT_TRIDENT, make_shared<Weapon>("Twilight Trident", 26, Item::ItemRarities::LEGENDARY, 50, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::HOLY_SPEAR, make_shared<Weapon>("Holy Spear", 22, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::POLEARM, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::MELEE)},
		
		// Weapons - Maces
		{ItemsIndex::IRON_MACE, make_shared<Weapon>("Iron Mace", 13, Item::ItemRarities::COMMON, 14, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::FLANGED_MACE, make_shared<Weapon>("Flanged Mace", 15, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SPIKED_MORNINGSTAR, make_shared<Weapon>("Spiked Morningstar", 16, Item::ItemRarities::RARE, 22, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::HOLY_FLAIL, make_shared<Weapon>("Holy Flail", 18, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DOOM_HAMMER, make_shared<Weapon>("Doom Hammer", 22, Item::ItemRarities::RARE, 35, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::WAR_CLUB, make_shared<Weapon>("War Club", 20, Item::ItemRarities::COMMON, 25, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DEMONSMASHER, make_shared<Weapon>("Demonsmasher", 25, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::STONE_CRUSHER, make_shared<Weapon>("Stone Crusher", 23, Item::ItemRarities::RARE, 38, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::BATTLE_MAUL, make_shared<Weapon>("Battle Maul", 26, Item::ItemRarities::UNCOMMON, 32, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SKULL_BREAKER, make_shared<Weapon>("Skull Breaker", 28, Item::ItemRarities::RARE, 42, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::SACRED_MACE, make_shared<Weapon>("Sacred Mace", 24, Item::ItemRarities::LEGENDARY, 50, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::DEATH_BRINGER, make_shared<Weapon>("Death Bringer", 30, Item::ItemRarities::LEGENDARY, 55, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::NIGHTMARE_MACE, make_shared<Weapon>("Nightmare Mace", 32, Item::ItemRarities::EPIC, 60, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::LIGHTNING_MAUL, make_shared<Weapon>("Lightning Maul", 29, Item::ItemRarities::RARE, 45, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		{ItemsIndex::BLOOD_SPIKE, make_shared<Weapon>("Blood Spike", 27, Item::ItemRarities::UNCOMMON, 40, Weapon::WeaponCategories::MACE, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
		
        // Weapons - Warhammers
        {ItemsIndex::IRON_WARHAMMER, make_shared<Weapon>("Iron Warhammer", 25, Item::ItemRarities::COMMON, 50, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::FLANGED_WARHAMMER, make_shared<Weapon>("Flanged Warhammer", 28, Item::ItemRarities::UNCOMMON, 55, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::GREAT_WARHAMMER, make_shared<Weapon>("Great Warhammer", 35, Item::ItemRarities::RARE, 65, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::DOOM_WARHAMMER, make_shared<Weapon>("Doom Warhammer", 40, Item::ItemRarities::LEGENDARY, 80, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::MOUNTAIN_CRUSHER, make_shared<Weapon>("Mountain Crusher", 45, Item::ItemRarities::EPIC, 90, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::SKULL_SMASHER, make_shared<Weapon>("Skull Smasher", 30, Item::ItemRarities::RARE, 60, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::DEMONBREAKER, make_shared<Weapon>("Demon Breaker", 40, Item::ItemRarities::LEGENDARY, 85, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::STONE_BREAKER, make_shared<Weapon>("Stone Breaker", 38, Item::ItemRarities::EPIC, 75, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BATTLE_WARHAMMER, make_shared<Weapon>("Battle Warhammer", 32, Item::ItemRarities::RARE, 70, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::THUNDERSTRIKE, make_shared<Weapon>("Thunderstrike", 42, Item::ItemRarities::LEGENDARY, 95, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::HOLY_WARHAMMER, make_shared<Weapon>("Holy Warhammer", 37, Item::ItemRarities::EPIC, 80, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::FROST_WARHAMMER, make_shared<Weapon>("Frost Warhammer", 36, Item::ItemRarities::RARE, 70, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::LIGHTNING_WARHAMMER, make_shared<Weapon>("Lightning Warhammer", 29, Item::ItemRarities::RARE, 45, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::EARTHSHAKER, make_shared<Weapon>("Earthshaker", 48, Item::ItemRarities::LEGENDARY, 100, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},
        {ItemsIndex::BLOODHAMMER, make_shared<Weapon>("Bloodhammer", 33, Item::ItemRarities::EPIC, 65, Weapon::WeaponCategories::WARHAMMER, Weapon::DamageTypes::IMPACT, Weapon::AttackStyles::MELEE)},

		// Weapons - Bows
		{ItemsIndex::SIMPLE_BOW, make_shared<Weapon>("Simple Bow", 5, Item::ItemRarities::COMMON, 8, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::LONG_BOW, make_shared<Weapon>("Long Bow", 7, Item::ItemRarities::UNCOMMON, 12, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::ELVEN_SHORTBOW, make_shared<Weapon>("Elven Shortbow", 6, Item::ItemRarities::RARE, 15, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::RECURVE_BOW, make_shared<Weapon>("Recurve Bow", 8, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::HUNTER_BOW, make_shared<Weapon>("Hunter Bow", 6, Item::ItemRarities::COMMON, 10, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::COMPOSITE_BOW, make_shared<Weapon>("Composite Bow", 10, Item::ItemRarities::UNCOMMON, 20, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::DARKWOOD_BOW, make_shared<Weapon>("Darkwood Bow", 7, Item::ItemRarities::RARE, 25, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::DRAGONBONE_BOW, make_shared<Weapon>("Dragonbone Bow", 12, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::EAGLE_EYE, make_shared<Weapon>("Eagle Eye", 11, Item::ItemRarities::RARE, 35, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::SHADOW_BOW, make_shared<Weapon>("Shadow Bow", 9, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::FIREWOOD_BOW, make_shared<Weapon>("Firewood Bow", 8, Item::ItemRarities::COMMON, 15, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::LIGHTBANE_BOW, make_shared<Weapon>("Lightbane Bow", 14, Item::ItemRarities::RARE, 45, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::SPIRITBOW, make_shared<Weapon>("Spiritbow", 16, Item::ItemRarities::EPIC, 50, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::BLOODED_BOW, make_shared<Weapon>("Blooded Bow", 13, Item::ItemRarities::UNCOMMON, 38, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::MOONLIGHT_BOW, make_shared<Weapon>("Moonlight Bow", 17, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::BOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		
		// Weapons - Crossbows
		{ItemsIndex::WOODEN_CROSSBOW, make_shared<Weapon>("Wooden Crossbow", 6, Item::ItemRarities::COMMON, 10, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::STEEL_CROSSBOW, make_shared<Weapon>("Steel Crossbow", 8, Item::ItemRarities::UNCOMMON, 15, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::SNIPER_CROSSBOW, make_shared<Weapon>("Sniper Crossbow", 10, Item::ItemRarities::RARE, 25, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::REPEATING_CROSSBOW, make_shared<Weapon>("Repeating Crossbow", 12, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::DRAGONBONE_CROSSBOW, make_shared<Weapon>("Dragonbone Crossbow", 15, Item::ItemRarities::EPIC, 35, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::HEAVY_CROSSBOW, make_shared<Weapon>("Heavy Crossbow", 18, Item::ItemRarities::RARE, 40, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::ASSAULT_CROSSBOW, make_shared<Weapon>("Assault Crossbow", 14, Item::ItemRarities::RARE, 30, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::IRONBOLT_CROSSBOW, make_shared<Weapon>("Ironbolt Crossbow", 10, Item::ItemRarities::COMMON, 20, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::OBSIDIAN_CROSSBOW, make_shared<Weapon>("Obsidian Crossbow", 11, Item::ItemRarities::RARE, 28, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::SIEGE_CROSSBOW, make_shared<Weapon>("Siege Crossbow", 25, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::QUICKFIRE_CROSSBOW, make_shared<Weapon>("Quickfire Crossbow", 9, Item::ItemRarities::UNCOMMON, 22, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::LONGBOLT_CROSSBOW, make_shared<Weapon>("Longbolt Crossbow", 13, Item::ItemRarities::RARE, 35, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::ARCANE_CROSSBOW, make_shared<Weapon>("Arcane Crossbow", 15, Item::ItemRarities::EPIC, 40, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::VENOM_CROSSBOW, make_shared<Weapon>("Venom Crossbow", 12, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		{ItemsIndex::FROSTSHOT_CROSSBOW, make_shared<Weapon>("Frostshot Crossbow", 14, Item::ItemRarities::LEGENDARY, 50, Weapon::WeaponCategories::CROSSBOW, Weapon::DamageTypes::PIERCE, Weapon::AttackStyles::RANGED)},
		
		// Weapons - Staves
		{ItemsIndex::WOODEN_STAFF, make_shared<Weapon>("Wooden Staff", 5, Item::ItemRarities::COMMON, 10, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ENCHANTED_STAFF, make_shared<Weapon>("Enchanted Staff", 6, Item::ItemRarities::UNCOMMON, 15, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ELDER_WAND, make_shared<Weapon>("Elder Wand", 7, Item::ItemRarities::RARE, 20, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::FIRE_STAFF, make_shared<Weapon>("Fire Staff", 8, Item::ItemRarities::RARE, 25, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ICE_STAFF, make_shared<Weapon>("Ice Staff", 8, Item::ItemRarities::RARE, 20, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::THUNDER_STAFF, make_shared<Weapon>("Thunder Staff", 9, Item::ItemRarities::EPIC, 30, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::NATURE_STAFF, make_shared<Weapon>("Nature Staff", 7, Item::ItemRarities::UNCOMMON, 15, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::BLOOD_STAFF, make_shared<Weapon>("Blood Staff", 8, Item::ItemRarities::EPIC, 35, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ARCANE_STAFF, make_shared<Weapon>("Arcane Staff", 10, Item::ItemRarities::LEGENDARY, 50, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::SHADOW_STAFF, make_shared<Weapon>("Shadow Staff", 9, Item::ItemRarities::LEGENDARY, 40, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::STAFF_OF_LIGHT, make_shared<Weapon>("Staff of Light", 10, Item::ItemRarities::LEGENDARY, 60, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::EARTHEN_STAFF, make_shared<Weapon>("Earthen Staff", 7, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::FROSTFIRE_STAFF, make_shared<Weapon>("Frostfire Staff", 11, Item::ItemRarities::EPIC, 45, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::STARWOOD_STAFF, make_shared<Weapon>("Starwood Staff", 10, Item::ItemRarities::RARE, 38, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::HOLY_WAND, make_shared<Weapon>("Holy Wand", 6, Item::ItemRarities::RARE, 20, Weapon::WeaponCategories::STAFF, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		
		// Weapons - Orbs
		{ItemsIndex::CRYSTAL_ORB, make_shared<Weapon>("Crystal Orb", 3, Item::ItemRarities::COMMON, 12, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::DARK_ORB, make_shared<Weapon>("Dark Orb", 4, Item::ItemRarities::UNCOMMON, 18, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::SUNSTONE_ORB, make_shared<Weapon>("Sunstone Orb", 5, Item::ItemRarities::RARE, 30, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::MOONSTONE_ORB, make_shared<Weapon>("Moonstone Orb", 5, Item::ItemRarities::RARE, 28, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::STAR_ORB, make_shared<Weapon>("Star Orb", 6, Item::ItemRarities::EPIC, 45, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ELEMENTAL_ORB, make_shared<Weapon>("Elemental Orb", 7, Item::ItemRarities::EPIC, 50, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::SORCERER_ORB, make_shared<Weapon>("Sorcerer Orb", 8, Item::ItemRarities::LEGENDARY, 70, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::CELESTIAL_ORB, make_shared<Weapon>("Celestial Orb", 9, Item::ItemRarities::LEGENDARY, 80, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::PHANTOM_ORB, make_shared<Weapon>("Phantom Orb", 5, Item::ItemRarities::RARE, 35, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::BLOOD_ORB, make_shared<Weapon>("Blood Orb", 7, Item::ItemRarities::EPIC, 55, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ORB_OF_WISDOM, make_shared<Weapon>("Orb of Wisdom", 6, Item::ItemRarities::RARE, 40, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::OBSIDIAN_ORB, make_shared<Weapon>("Obsidian Orb", 7, Item::ItemRarities::EPIC, 48, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ETHEREAL_ORB, make_shared<Weapon>("Ethereal Orb", 8, Item::ItemRarities::LEGENDARY, 85, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::ORB_OF_DOOM, make_shared<Weapon>("Orb of Doom", 10, Item::ItemRarities::LEGENDARY, 100, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)},
		{ItemsIndex::DIVINE_ORB, make_shared<Weapon>("Divine Orb", 9, Item::ItemRarities::LEGENDARY, 95, Weapon::WeaponCategories::ORB, Weapon::DamageTypes::MAGIC_DAMAGE, Weapon::AttackStyles::MAGIC)}
    };
    return Items;
}

// Initialize a map that statically stores items descriptions associated with the items name
const map<string, string> ItemsInitializer::getDescriptions() {
    static map<string, string> Descriptions {
		// Miscellaneous - Tools
		{"Wooden Hammer", "A basic hammer made of wood, suitable for light tasks such as crafting and repairing."},
		{"Iron Tongs", "Strong iron tongs used to grip and manipulate hot objects, ideal for blacksmithing."},
		{"Leather Pouch", "A small pouch made of leather, perfect for carrying small tools or herbs."},
		{"Carpenter's Saw", "A finely crafted saw used by carpenters to cut wood with precision."},
		{"Blacksmith's Hammer", "A heavy hammer used by blacksmiths for forging and shaping metal."},
		{"Hunter's Trap", "A sturdy trap used by hunters to catch wild animals in the forest."},
		{"Fishing Rod", "A simple rod used for fishing, ideal for catching small fish in rivers and lakes."},
		{"Cooking Pot", "A large pot used for cooking stews, soups, and other meals over an open flame."},
		{"Healer's Kit", "A kit containing various herbs, bandages, and potions for healing minor injuries."},
			
		// Miscellaneous - Magical Items
		{"Enchanted Stone", "A small stone imbued with magical energy, often used as a focus for spells."},
		{"Alchemist's Kit", "A kit containing all the essential tools for brewing potions and crafting alchemical mixtures."},
		{"Mystic Talisman", "A rare talisman said to grant the wearer mystical protection from dark forces."},
		{"Ancient Scroll", "An old scroll containing arcane knowledge, often written in a language long forgotten."},
		{"Wizard's Cloak", "A finely crafted cloak worn by wizards, it provides protection from magical attacks."},
		{"Mage's Orb", "A magical orb that enhances the powers of the mage, glowing with an inner light."},
		{"Shimmering Crystal", "A small crystal that shimmers with light, believed to possess magical properties."},
		{"Teleportation Rune", "A rare rune that allows the user to teleport to any location they have previously visited."},
		{"Cursed Ring", "A ring imbued with dark magic, it grants power at a terrible cost."},
		
		// Miscellaneous - Food
		{"Dried Meat", "A preserved meat that has been dried for long-term storage, a staple in survival rations."},
		{"Healing Herbs", "A bundle of herbs known for their healing properties, commonly used to treat wounds."},
		{"Apple", "A crisp, sweet apple, commonly found in orchards and enjoyed as a refreshing snack."},
		{"Honey Jar", "A jar filled with golden honey, often used to sweeten food or drinks."},
		{"Bread Loaf", "A freshly baked loaf of bread, soft and warm, perfect for a hearty meal."},
		{"Cheese Wheel", "A round wheel of cheese, aged to perfection with a rich, creamy flavor."},
		{"Herb Soup", "A flavorful soup made with a variety of herbs, known for its restorative qualities."},
		{"Spiced Wine", "A sweet wine infused with spices, offering a warming and comforting drink."},
		{"Dragonfruit", "A rare and exotic fruit, its vibrant pink skin and sweet flesh are said to have magical properties."},
				
		// Weapons - Swords
		{"Iron Sword", "A basic sword crafted from iron. It offers moderate damage and durability."},
		{"Steel Short Sword", "A smaller sword made of steel, offering quick strikes and better durability."},
		{"Bronze Long Sword", "A long sword made from bronze, offering balanced damage and control."},
		{"Knight Blade", "A finely crafted blade used by knights, offering enhanced damage and durability."},
		{"Assassin Dagger", "A small, light dagger favored by assassins. It deals high damage but lacks durability."},
		{"Rune Sword", "A sword inscribed with ancient runes. It deals magical damage alongside physical slashes."},
		{"Silver Rapier", "A slender rapier made of silver, perfect for piercing attacks with speed and precision."},
		{"Shadow Fang", "A mystical sword infused with shadow magic, dealing both physical and shadow damage."},
		{"Bloodthirst Blade", "A cursed blade that absorbs life force with every strike, dealing high damage."},
		{"Celestial Saber", "A sword blessed by celestial powers. It deals magical damage with a graceful shine."},
		{"Frostbite Blade", "A chilling blade that freezes enemies on contact, slowing them and dealing ice damage."},
		{"Flame Tongue", "A sword engulfed in flames, dealing fire damage to enemies on each strike."},
		{"Starfire Short Sword", "A short sword with a star-like glow. It deals both physical and radiant damage."},
		{"Blade of the Winds", "A legendary blade known for its speed and sharpness, capable of slicing through the wind."},
		{"Eclipse Sword", "A sword that channels dark magic, capable of dealing massive magical damage."},
		
		// Weapons - Greatswords
		{"Iron Greatsword", "A massive sword made from iron, offering great damage and reach."},
		{"Silver Greatsword", "A greatsword made of silver, combining heavy damage with better durability."},
		{"Dragon Slayer", "A massive sword designed to slay dragons, dealing massive physical damage."},
		{"Darksteel Claymore", "A large claymore made from darksteel, known for its immense power and durability."},
		{"Ancient Blade", "An ancient sword of great power, passed down through generations, capable of dealing massive damage."},
		{"Titan Sword", "A giant sword capable of crushing enemies with incredible force."},
		{"Berserker Claymore", "A claymore designed for berserkers, dealing great damage at the cost of defense."},
		{"Sunforged Greatsword", "A legendary sword forged under the sun, dealing immense fire damage."},
		{"Doombringer", "A greatsword forged in the depths of hell, capable of causing destruction with every swing."},
		{"Obsidian Greatblade", "A massive obsidian blade with the power to tear through even the toughest of armor."},
		{"Crusader Greatsword", "A sword used by crusaders in their holy battles, dealing great physical damage."},
		{"Warlord Blade", "A blade favored by warlords, capable of cleaving through hordes of enemies."},
		{"Thunderclap Greatsword", "A sword that channels the power of thunder, dealing both physical and impact damage."},
		{"Lightbringer Blade", "A divine sword that emits a brilliant light, dealing magic damage to enemies."},
		{"Abyssal Cleaver", "A massive sword forged in the abyss, dealing immense physical damage."},

		// Weapons - Axes
        {"Iron Axe", "A basic axe made from iron, offering decent damage for melee combat."},
        {"Steel Battleaxe", "A battleaxe crafted from steel, known for its durability and strength."},
        {"Bronze Handaxe", "A small but effective handaxe made from bronze, useful for close combat."},
        {"Battle Axe of the King", "A legendary battleaxe wielded by kings, dealing immense damage with every swing."},
        {"Elven Waraxe", "A lightweight and swift waraxe crafted by elves, combining elegance with power."},
        {"Frost Axe", "An axe imbued with frost magic, capable of freezing enemies upon impact."},
        {"Rune Axe", "A rune-inscribed axe that draws on ancient power, delivering devastating blows."},
        {"Mystic Axe", "A mystic axe imbued with powerful magic, capable of cutting through anything."},
        {"Thunderstrike Axe", "An axe that channels the power of lightning, shocking enemies on impact."},
        {"Darkwood Axe", "A sturdy axe made from darkwood, offering solid damage with increased durability."},
        {"Bloodaxe", "A fearsome axe known for its thirst for blood, dealing increased damage with each kill."},
        {"Fireaxe", "A battleaxe forged in fire, capable of causing burning damage to enemies."},
        {"Celestial Battleaxe", "A divine battleaxe, radiant and powerful, dealing tremendous physical damage."},
        {"Vampiric Axe", "A cursed axe that draws the life force from its victims, healing the wielder."},
        {"Stormaxe", "An axe imbued with storm magic, capable of summoning lightning upon impact."},
		
        // Weapons - Greataxes
        {"Iron Greataxe", "A massive iron greataxe, designed for heavy swings and devastating blows."},
        {"Steel Greataxe", "A steel greataxe that combines strength and durability for powerful strikes."},
        {"Titan Greataxe", "A titanic weapon capable of crushing foes with immense force."},
        {"Dragonbone Greataxe", "A fearsome greataxe made from dragonbone, offering both strength and durability."},
        {"Demonic Greataxe", "A demonic greataxe forged in the hellish realms, capable of terrifying destruction."},
        {"Sunforged Greataxe", "A celestial weapon forged by the sun's flame, dealing radiant damage with every swing."},
        {"Crystal Greataxe", "A crystal-infused greataxe that can shatter enemy defenses with ease."},
        {"Warlord Greataxe", "A battle-hardened greataxe used by warlords to dominate the battlefield."},
        {"Obsidian Greataxe", "A greataxe forged from obsidian, its edges sharp enough to pierce through armor."},
        {"Frost Greataxe", "A frost-infused greataxe that freezes enemies with every strike."},
        {"Berserker Greataxe", "A greataxe designed for berserkers, offering great damage but at the cost of reduced defense."},
		
		// Weapons - Polearms
		{"Iron Lance", "A basic polearm crafted from iron, suitable for both thrusting and defensive actions."},
		{"Steel Spear", "A steel spear offering increased durability and precision for piercing attacks."},
		{"Pike", "A long spear used for reaching distant enemies, ideal for thrusting attacks."},
		{"Halberd", "A polearm with a broad axe blade, designed for impact and slashing damage."},
		{"Dragonbone Trident", "A trident made from dragonbone, perfect for piercing enemies with great force."},
		{"Glaive", "A polearm with a single-edged blade, ideal for slashing and cutting through enemies."},
		{"Long Poleaxe", "A long poleaxe that combines the reach of a polearm with the lethality of an axe."},
		{"Phantom Spear", "A spear with a mysterious aura, capable of piercing through enemy armor effortlessly."},
		{"Vanguard Lance", "A lance used by vanguard soldiers, designed to penetrate enemy ranks and cause havoc."},
		{"War Pike", "A pike designed for warfare, offering great reach and deadly piercing potential."},
		{"Spear of Destiny", "A legendary spear said to alter the course of battles, offering devastating piercing damage."},
		{"Frost Halberd", "A halberd that deals ice damage, freezing enemies upon impact and reducing their mobility."},
		{"Fiery Glaive", "A glaive imbued with fire, dealing both physical and fire damage with each swing."},
		{"Twilight Trident", "A trident forged in the twilight hours, dealing both piercing and magic damage."},
		{"Holy Spear", "A divine spear that channels holy energy, capable of dealing devastating piercing damage."},
		
		// Weapons - Maces
		{ "Iron Mace", "A sturdy mace forged from iron, suitable for smashing through armor and bones alike." },
		{ "Flanged Mace", "A mace with sharp, protruding flanges designed to cause maximum damage with each strike." },
		{ "Spiked Morningstar", "A fearsome morningstar, its spiked ball designed to puncture even the toughest armor." },
		{ "Holy Flail", "A blessed flail that radiates divine power, capable of smiting the unholy." },
		{ "Doom Hammer", "A massive hammer, heavy and unyielding, with the power to bring doom upon any foe." },
		{ "War Club", "A simple yet effective club used by warriors in battle, capable of devastating blows." },
		{ "Demonsmasher", "A legendary mace forged to deal with the infernal, capable of shattering demonic defenses." },
		{ "Stone Crusher", "A powerful weapon designed to break through stone and bone with ease." },
		{ "Battle Maul", "A massive maul used in battle, able to deliver crushing blows to opponents." },
		{ "Skull Breaker", "A heavy mace with a terrifying reputation, capable of breaking skulls with a single strike." },
		{ "Sacred Mace", "A rare and revered mace, its holy power is said to bring justice to the wicked." },
		{ "Death Bringer", "A mace so powerful, it is said that each strike brings death to those who stand in its way." },
		{ "Nightmare Mace", "A mace forged in the darkest pits, its strikes haunting the dreams of those it hits." },
		{ "Lightning Maul", "A maul charged with the power of lightning, delivering shockingly devastating blows." },
		{ "Blood Spike", "A vicious mace covered in jagged spikes, often used to spill the blood of its victims." },

        // Weapons - Warhammers
        { "Iron Warhammer", "A basic warhammer made of iron, ideal for smashing through armor. Commonly used by soldiers." },
        { "Flanged Warhammer", "A warhammer with flanged edges, designed for better penetration of armor. Uncommon but deadly." },
        { "Great Warhammer", "A massive, two-handed warhammer designed for devastating blows. Rare and sought after by warriors." },
        { "Doom Warhammer", "A legendary hammer capable of destroying even the toughest enemies. A symbol of destruction." },
        { "Mountain Crusher", "A heavy warhammer made to break through mountain rock. Epic in rarity, known for its immense power." },
        { "Skull Smasher", "A brutal weapon designed to crush skulls. Rare, and favored by barbarians and mercenaries." },
        { "Demon Breaker", "A warhammer forged to slay demons, with an aura of death around it. Legendary in strength." },
        { "Stone Breaker", "A powerful hammer capable of crushing stone and bone alike. Known for its overwhelming force." },
        { "Battle Warhammer", "A warhammer designed for close combat, balanced for speed and power. Rare among warriors." },
        { "Thunderstrike", "A warhammer that crackles with the power of lightning. Legendary in nature, often used by stormmages." },
        { "Holy Warhammer", "A warhammer imbued with divine power, capable of smiting evil. Epic and revered by clerics." },
        { "Frost Warhammer", "A warhammer with a freezing aura that chills enemies to the bone. Rare and favored by frost mages." },
        { "Lightning Warhammer", "A maul with lightning-infused power, capable of shocking foes upon impact. Rare and powerful." },
        { "Earthshaker", "An enormous warhammer said to shake the very earth with each strike. A legendary weapon of mass destruction." },
        { "Bloodhammer", "A warhammer stained with the blood of its countless victims. Known for its brutal efficiency and power." },
		
		// Weapons - Bows
		{ "Simple Bow", "A basic bow used for hunting, capable of firing arrows with decent accuracy and power." },
		{ "Long Bow", "A long-range bow designed for accuracy, favored by archers for its power and distance." },
		{ "Elven Shortbow", "A finely crafted shortbow made by elves, quick to draw and incredibly accurate." },
		{ "Recurve Bow", "A bow with a curved design, providing greater power and accuracy compared to standard bows." },
		{ "Hunter Bow", "A reliable bow used by hunters, designed for both power and precision." },
		{ "Composite Bow", "A bow crafted from different materials, giving it a balance of power and flexibility." },
		{ "Darkwood Bow", "A bow crafted from the wood of the darkwood trees, its arrows capable of piercing even the strongest armor." },
		{ "Dragonbone Bow", "A bow forged from the bones of a dragon, giving it incredible strength and the ability to pierce through the toughest enemies." },
		{ "Eagle Eye", "A bow with unparalleled precision, capable of striking a target from a great distance." },
		{ "Shadow Bow", "A dark, elusive bow that seems to blend into its surroundings, perfect for stealthy shots." },
		{ "Firewood Bow", "A simple bow made from firewood, though it may seem basic, it still delivers a strong shot." },
		{ "Lightbane Bow", "A bow imbued with the power to combat the forces of darkness, perfect for dealing with undead and demonic enemies." },
		{ "Spiritbow", "A bow crafted from ethereal material, capable of shooting arrows that can strike both the physical and spiritual realms." },
		{ "Blooded Bow", "A bow that thirsts for blood, capable of dealing powerful shots that increase in strength with each enemy slain." },
		{ "Moonlight Bow", "A legendary bow said to harness the power of the moon, delivering ethereal shots that are impossible to dodge." },
		
		
		// Weapons - Crossbows
		{"Wooden Crossbow", "A simple crossbow made of wood, lightweight and easy to use, ideal for novice archers."},
		{"Steel Crossbow", "A sturdy steel crossbow offering improved durability and range, favored by skilled hunters."},
		{"Sniper Crossbow", "A long-range crossbow designed for precision shots, with increased damage for distant targets."},
		{"Repeating Crossbow", "A crossbow that fires multiple bolts in quick succession, favored for rapid-fire combat."},
		{"Dragonbone Crossbow", "A rare and powerful crossbow crafted from the bones of dragons, known for its immense strength and precision."},
		{"Heavy Crossbow", "A massive crossbow requiring great strength to wield, capable of dealing devastating damage."},
		{"Assault Crossbow", "A crossbow designed for tactical combat, with rapid reload and powerful bolts for modern warfare."},
		{"Ironbolt Crossbow", "A simple crossbow with iron bolts, suitable for everyday use by novice hunters and adventurers."},
		{"Obsidian Crossbow", "A rare crossbow made from obsidian, renowned for its sharp, unbreakable bolts."},
		{"Siege Crossbow", "A massive, powerful crossbow designed for use in sieging enemy fortifications, capable of firing large bolts."},
		{"Quickfire Crossbow", "A lightweight crossbow that allows for rapid reloading and quick, successive shots."},
		{"Longbolt Crossbow", "A crossbow equipped with longer bolts, providing increased range and damage potential."},
		{"Arcane Crossbow", "A magical crossbow that channels arcane energy into each shot, dealing devastating damage to enemies."},
		{"Venom Crossbow", "A crossbow infused with venom, causing each bolt to poison enemies upon impact."},
		{"Frostshot Crossbow", "A crossbow imbued with frost magic, capable of freezing enemies with every bolt fired."},
		
		
		// Weapons - Staves    
		{"Wooden Staff", "A basic wooden staff, commonly used by novice spellcasters to channel their magical energy."},
		{"Enchanted Staff", "A staff imbued with enchantments that increase a caster's power and control over magic."},
		{"Elder Wand", "A rare and ancient wand, sought after by powerful sorcerers for its immense magical potential."},
		{"Fire Staff", "A staff that channels the destructive power of fire, used by pyromancers to unleash fiery spells."},
		{"Ice Staff", "A staff that controls the element of ice, allowing its wielder to summon powerful ice-based magic."},
		{"Thunder Staff", "A magical staff that channels the power of lightning, capable of unleashing devastating electrical attacks."},
		{"Nature Staff", "A staff that draws power from nature, allowing its wielder to manipulate plants and summon creatures of the wild."},
		{"Blood Staff", "A staff forged from the essence of life itself, granting its wielder the ability to manipulate blood magic."},
		{"Arcane Staff", "A legendary staff that channels pure arcane energy, granting its wielder immense magical power."},
		{"Shadow Staff", "A staff crafted from the shadows, allowing its wielder to manipulate dark magic and summon shadows."},
		{"Staff of Light", "A powerful staff that radiates pure light, used by holy spellcasters to heal and protect allies."},
		{"Earthen Staff", "A staff that channels the earth's energy, allowing its wielder to manipulate rocks, soil, and the ground beneath them."},
		{"Frostfire Staff", "A staff that combines the destructive powers of fire and ice, capable of unleashing both elements in powerful bursts."},
		{"Starwood Staff", "A rare staff crafted from the wood of ancient star trees, imbuing its wielder with the power of the cosmos."},
		{"Holy Wand", "A wand imbued with holy magic, used by clerics and paladins to heal and protect the righteous."},
		
		
		// Weapons - Orbs
		{"Crystal Orb", "A simple orb made of crystal, used by novice spellcasters to focus their magical energies."},
		{"Dark Orb", "An orb infused with dark magic, used by practitioners of forbidden arts to enhance their powers."},
		{"Sunstone Orb", "A radiant orb made from sunstone, used by light mages to cast powerful beams of sunlight."},
		{"Moonstone Orb", "A mystical orb crafted from moonstone, favored by mages who wield the power of the moon."},
		{"Star Orb", "A rare orb made from star fragments, imbuing its wielder with cosmic energy for devastating magical effects."},
		{"Elemental Orb", "An orb that contains the power of the four elements, granting its wielder control over fire, water, earth, and air."},
		{"Sorcerer Orb", "A legendary orb used by sorcerers to amplify their magical power and cast powerful, destructive spells."},
		{"Celestial Orb", "An orb infused with celestial energy, granting its wielder control over the stars and the heavens themselves."},
		{"Phantom Orb", "A ghostly orb that channels spectral energy, allowing its wielder to summon and control spirits."},
		{"Blood Orb", "An orb filled with the essence of life, used by necromancers to control blood magic and raise the dead."},
		{"Orb of Wisdom", "A rare orb that grants its wielder enhanced knowledge and insight into the arcane arts."},
		{"Obsidian Orb", "A dark, obsidian orb that channels powerful dark magic, often used by necromancers and shadow mages."},
		{"Ethereal Orb", "A translucent orb that grants its wielder control over the ethereal plane, allowing them to summon and banish spirits."},
		{"Orb of Doom", "A powerful orb of destruction, capable of unleashing devastating magical blasts that decimate enemies."},
		{"Divine Orb", "An orb imbued with divine energy, used by priests and paladins to channel the powers of the gods in battle."}		
    };
    return Descriptions;
}